### ISSUE TITLE
Do not update tokens for projects that were uninstalled 

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/tokman#39] opened 2021-12-14 09:16 UTC
We check all the projects that installed the GitHub application even if they uninstalled the app later on.

We might need this for the implementation: packit/ogr#666

And here is a related sentry issue: https://sentry.io/share/issue/974834b4b2c34429a5bde2d30c5d9000/

**Comment by mfocko** [comment] 2022-01-07 11:10
I would probably say it's undefined behavior (under the assumption it's `triggered job → suspend → babysit checks`)

* `ogr` is unrelated, since tokman uses directly `PyGithub`
  * unless you suggest ignoring unfinished jobs on service-side
* it looks like the issue is triggered by checking for finished Copr build, so it seems to me the build was triggered, installation suspended… one way or another it would cause an issue somewhere
  * there is also a possibility it's coming from the periodic job over all unfinished jobs, that might be easier to solve
  * nevertheless (normal babysit after trigger or periodic), we would probably need some way to determine if app is installed and filter/ignore such repositories

**Comment by csomh** [comment] 2022-09-06 06:57
This should be fixed in other areas, already.

**Closed by csomh** 2022-09-06 06:57 UTC
Labels: bug
